language: node_js
node_js:
- "6.10.3"
services:
- postgresql
addons:
  sauce_connect:
    username: $SAUCE_USERNAME
    access_key: $SAUCE_ACCESS_KEY
env:
  global:
  - secure: TODO
before_script:
- psql -c 'CREATE DATABASE spoke_test;' -U postgres
- psql -c "CREATE USER spoke_test WITH PASSWORD 'spoke_test';" -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE spoke_test TO spoke_test;' -U postgres

- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- npm run test-coverage
- npm run dev-nowrap &
- sleep 120 # TODO: Grep stdout or something to determine that the server is active. Or do this in the test setup.
- npm run test-e2e --saucelabs
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
